name: Omniscience Release

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package install --file pom.xml
    - name: Deploy to Github Packages
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/Lord-of-the-Craft -Dtoken=${{ secrets.GITHUB_TOKEN }}
